 const ActionTypes = {
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    CURRENTUSERERROR: "CURRENTUSERERROR",
    SEEKERHOMEDATA: "SEEKERHOMEDATA",
    DONORHOMEDATA: "DONORHOMEDATA",
    DONORPROFILE : "DONORPROFILE",
    BLOODGROUP : "BLOODGROUP",
    LOGOUT : "LOGOUT",
    SIGNINERROR : "SIGNINERROR"

}

export default ActionTypes;
